# Generated by Django 5.0.6 on 2024-05-11 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TMSITIAnnouncement',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tmsiti.abstractbasemodel')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_published', models.DateField()),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcement',
                'ordering': ['-date_published'],
            },
            bases=('app_tmsiti.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='TMSITIManagement',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tmsiti.abstractbasemodel')),
                ('job_name', models.CharField(max_length=500)),
                ('fullname', models.CharField(max_length=500)),
                ('admission_days', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('specialization_bachelor', models.CharField(max_length=500)),
                ('master_specialty', models.CharField(max_length=500)),
                ('employee_image', models.ImageField(upload_to='employees/')),
            ],
            options={
                'verbose_name_plural': 'Managements',
                'db_table': 'managements',
            },
            bases=('app_tmsiti.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='TMSITINews',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tmsiti.abstractbasemodel')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_published', models.DateField()),
                ('image', models.ImageField(upload_to='news/')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ['-date_published'],
            },
            bases=('app_tmsiti.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='TMSITIStandard',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tmsiti.abstractbasemodel')),
                ('standard_name', models.CharField(max_length=50)),
                ('standard_code', models.IntegerField()),
                ('standard_title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Standards',
                'db_table': 'standards',
            },
            bases=('app_tmsiti.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='TMSITIStructuralDivision',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tmsiti.abstractbasemodel')),
                ('staff_job', models.CharField(max_length=255)),
                ('staff_fullname', models.CharField(max_length=255)),
                ('staff_phone_number', models.IntegerField()),
                ('staff_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'StructuralDivisions',
                'db_table': 'structural_division',
            },
            bases=('app_tmsiti.abstractbasemodel',),
        ),
    ]
