# Generated by Django 5.0.6 on 2024-05-11 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tmsiti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMSITIContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('appeal_text', models.TextField()),
                ('appeal_file', models.FileField(null=True, upload_to='appeals/')),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tmsiti.tmsitimanagement')),
            ],
        ),
    ]
