# Generated by Django 5.0.6 on 2024-05-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tmsiti', '0002_tmsiticontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMSITIBuildingReglements',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tmsiti.abstractbasemodel')),
                ('reglement_number', models.IntegerField()),
                ('reglement_code', models.CharField(max_length=10)),
                ('reglement_title', models.CharField(max_length=500)),
                ('reglement_file', models.FileField(upload_to='buildings/')),
            ],
            bases=('app_tmsiti.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='TMSITIElecStandards',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tmsiti.abstractbasemodel')),
                ('doc_number', models.IntegerField()),
                ('doc_title', models.CharField(max_length=500)),
                ('doc_type', models.CharField(max_length=500)),
                ('doc_sign', models.CharField(max_length=500, null=True)),
                ('doc_approved_year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'ElecStandards',
                'db_table': 'elec_standards',
            },
            bases=('app_tmsiti.abstractbasemodel',),
        ),
    ]
